### ISSUE TITLE
/report sometimes returns a timeout error

### ISSUE THREAD

**Issue by totallytavi** [FederationStudios/IRF_Administration#142]
This might be due to me forgetting to handle time errors. But still, it could also arise from the ticekts function. Not sure. May investigate at a later time

**Comment by totallytavi** [comment]
```
Error [InteractionCollectorError]: Collector received no interactions before ending with reason: time
at InteractionCollector.<anonymous> (/home/tavi/IRF_Administration/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:290:21)
at Object.onceWrapper (node:events:628:26)
at InteractionCollector.emit (node:events:525:35)
at InteractionCollector.stop (/home/tavi/IRF_Administration/node_modules/discord.js/src/structures/interfaces/Collector.js:233:10)
at Timeout.<anonymous> (/home/tavi/IRF_Administration/node_modules/discord.js/src/structures/interfaces/Collector.js:96:61)
at listOnTimeout (node:internal/timers:573:17)
at process.processTimers (node:internal/timers:514:7)
```
One example
