### ISSUE TITLE
Profile command fails on certain users

### ISSUE THREAD

**Issue by totallytavi** [FederationStudios/IRF_Administration#146]
Example error logs:
```
TypeError: Cannot read properties of undefined (reading '0')
at Module.run (file:///home/tavi/IRF_Administration/dist/commands/profile.js:255:31)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
```
TypeError: Cannot read properties of undefined (reading '0')
at Module.run (file:///home/tavi/IRF_Administration/dist/commands/profile.js:255:31)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by totallytavi** [comment]
Found the issue. Wrote a bad line. Fixed soon
