### ISSUE TITLE
Cannot run the /report command

### ISSUE THREAD

**Issue by totallytavi** [FederationStudios/IRF_Administration#150]
You cannot run the command at all. It just fails and before anything shows up, you're asked to contact an Engineer. Potentially features paginationRow as that's in the stacktrace.

Stacktraces
```js
TypeError: interaction.editReply is not a function
at paginationRow (file:///home/tavi/IRF_Administration/dist/functions.js:253:14)
at getDivision (file:///home/tavi/IRF_Administration/dist/functions/tickets.js:347:34)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Module.run (file:///home/tavi/IRF_Administration/dist/commands/report.js:20:22)
```
```js
TypeError: interaction.editReply is not a function
at paginationRow (file:///home/tavi/IRF_Administration/dist/functions.js:253:14)
at getDivision (file:///home/tavi/IRF_Administration/dist/functions/tickets.js:347:34)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Module.run (file:///home/tavi/IRF_Administration/dist/commands/report.js:20:22)
```
```js
TypeError: interaction.editReply is not a function
at paginationRow (file:///home/tavi/IRF_Administration/dist/functions.js:253:14)
at getDivision (file:///home/tavi/IRF_Administration/dist/functions/tickets.js:347:34)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Module.run (file:///home/tavi/IRF_Administration/dist/commands/report.js:20:22)
```

**Comment by totallytavi** [comment]
Judging by that stacktrace, it's probably invoked from paginationRow which travels through getDivision and subsequently report.js
