### ISSUE TITLE
Check command refuses to run properly

### ISSUE THREAD

**Issue by totallytavi** [FederationStudios/IRF_Administration#165]
Likely an issue with `check.js:103:18` according to one stacktrace. Probably an empty variable I didn't account for

**Comment by totallytavi** [comment]
Stacktrace used in initial comment
```js
DiscordAPIError[50035]: Invalid Form Body
embeds[0].fields[0].value[BASE_TYPE_REQUIRED]: This field is required
at handleErrors (/home/tavi/IRF_Administration/node_modules/@discordjs/rest/dist/index.js:640:13)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async SequentialHandler.runRequest (/home/tavi/IRF_Administration/node_modules/@discordjs/rest/dist/index.js:1021:23)
at async SequentialHandler.queueRequest (/home/tavi/IRF_Administration/node_modules/@discordjs/rest/dist/index.js:862:14)
at async REST.request (/home/tavi/IRF_Administration/node_modules/@discordjs/rest/dist/index.js:1387:22)
at async InteractionWebhook.editMessage (/home/tavi/IRF_Administration/node_modules/discord.js/src/structures/Webhook.js:338:15)
at async ChatInputCommandInteraction.editReply (/home/tavi/IRF_Administration/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:158:17)
at async Module.run (file:///home/tavi/IRF_Administration/dist/commands/check.js:103:18)
```

**Comment by totallytavi** [comment]
I think I've fixed this, will re-open as needed
